Repository final-semicolon/div, pull requests merged in 2024-07, with the labels that each got.

#62 [fix] global css
  src/app/globals.css
Labels: Chore

#75 update:folder architecture
  src/assets/fonts/index.ts
  src/assets/images/index.ts
  src/providers/TanstackQueryProvider.tsx
Labels: Chore

#72 feature/Mypage UI profile
  next.config.mjs
  src/app/(home)/(profile)/_components/MyActivities.tsx
  src/app/(home)/(profile)/_components/ProfileContent.tsx
  src/app/(home)/(profile)/_components/ProfileSetting.tsx
  src/app/(home)/(profile)/_components/ProfileSidebar.tsx
  src/app/(home)/(profile)/_components/index.ts
  src/app/(home)/(profile)/_components/myactivities/BookmarksList.tsx
  src/app/(home)/(profile)/_components/myactivities/CommentCard.tsx
  src/app/(home)/(profile)/_components/myactivities/LikesList.tsx
  src/app/(home)/(profile)/_components/myactivities/MyActivitiesHeader.tsx
  src/app/(home)/(profile)/_components/myactivities/MyPostsList.tsx
  src/app/(home)/(profile)/_components/myactivities/PostCard.tsx
  src/app/(home)/(profile)/_components/setting/EditableField.tsx
  src/app/(home)/(profile)/layout.tsx
  src/app/(home)/(profile)/profile/activities/page.tsx
  src/app/(home)/(profile)/profile/edit/page.tsx
  src/app/(home)/(profile)/profile/page.tsx
  src/app/(home)/(profile)/profile/settings/page.tsx
  src/store/useActiveTabStore.ts
Labels: Feature_UI

#76 [feature] posting UI
  package-lock.json
  package.json
  src/app/(home)/(posting)/posting/page.tsx
  src/app/(home)/(upsert)/_components/UpsertTheme.tsx
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormCategoryBox.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormContentArea.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormSubmitButton.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormTagInput.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormTitleInput.tsx
  src/app/(home)/(upsert)/_components/edit/editform/categorybox/ForumCategoryDropDown.tsx
  src/app/(home)/(upsert)/_components/edit/editform/categorybox/PostingCategory.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormCategoryBox.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormContentArea.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormSubmitButton.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormTagInput.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormTitleInput.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/categorybox/ForumCategoryDropDown.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/categorybox/PostingCategory.tsx
  src/app/(home)/(upsert)/edit/[id]/page.tsx
  src/app/(home)/(upsert)/posting/page.tsx
  src/app/layout.tsx
  src/constants/posting.ts
  src/types/upsert.ts
Labels: Chore, Feature_UI

#77 update: signup ui, middleware 초기설정, zustand 유저전역관리 설정
  src/app/(home)/(auth)/_components/CheckboxGroup.tsx
  src/app/(home)/(auth)/_components/InputField.tsx
  src/app/(home)/(auth)/_components/SignupButton.tsx
  src/app/(home)/(auth)/_components/SignupForm.tsx
  src/app/(home)/(auth)/login/page.tsx
  src/app/(home)/(auth)/signin/page.tsx
  src/app/(home)/(auth)/signup/page.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/index.ts
  src/app/api/auth/signup/route.ts
  src/middleware.ts
  src/store/useUserStore.ts
  src/supabase/middleware.ts
Labels: Feature_UI

#78 update: signup api 설정
  src/app/api/auth/signup/route.ts
Labels: Feature_API

#79 update: login ui 구현
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(auth)/login/page.tsx
Labels: Feature_UI

#80 update: login api 설정
  src/app/api/auth/login/route.ts
Labels: Feature_API

#82 update: context로 유저관리 생성 및 기존 zustand 삭제, 관련 코드 수정 및 컴포넌트 추가 분리
  src/app/(home)/(auth)/_components/CheckboxGroup.tsx
  src/app/(home)/(auth)/_components/InputField.tsx
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(auth)/_components/NicknameCheck .tsx
  src/app/(home)/(auth)/_components/PasswordFields.tsx
  src/app/(home)/(auth)/_components/SignupForm.tsx
  src/app/(home)/(terms)/legal/privacy/page.tsx
  src/app/(home)/(terms)/legal/terms/page.tsx
  src/app/api/auth/check-nickname/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/auth/logout/index.ts
  src/app/api/auth/logout/route.ts
  src/app/api/auth/me/route.ts
  src/app/api/auth/signup/route.ts
  src/app/api/auth/update-nickname/route.ts
  src/app/layout.tsx
  src/context/auth.context.tsx
  src/store/useUserStore.ts
Labels: Feature_API

#83 Feature/forum posts api
  package-lock.json
  package.json
  src/app/(home)/(posts)/_components/conference/ForumPosts.tsx
  src/app/(home)/(posts)/_components/conference/ForumPostsWithCategoryAndSort.tsx
  src/app/(home)/(posts)/_components/conference/PostCard.tsx
  src/app/(home)/(posts)/_components/conference/ScrollToTopButton.tsx
  src/app/(home)/(posts)/conference/page.tsx
  src/app/api/posts/conference/route.ts
  src/hooks/conference/useFetchForumPosts.ts
  src/types/posts/forumTypes.ts
  src/types/supabase.ts
Labels: Feature_API

#85 update:conference file name change
  src/app/(home)/(posts)/_components/forum/ForumPosts.tsx
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/app/(home)/(posts)/_components/forum/ScrollToTopButton.tsx
  src/app/(home)/(posts)/conference/[id]/page.tsx
  src/app/(home)/(posts)/conference/page.tsx
  src/app/(home)/(posts)/forum/[id]/page.tsx
  src/app/(home)/(posts)/forum/page.tsx
  src/app/(home)/_components/PostsLink.tsx
  src/app/api/posts/forum/route.ts
  src/hooks/forum/useFetchForumPosts.ts
Labels: Chore

#86 Feature/header api
  src/app/(home)/(posts)/notification/page.tsx
  src/app/(home)/page.tsx
  src/app/layout.tsx
  src/assets/images/Logo.tsx
  src/assets/images/SearchButton.tsx
  src/components/header/Header.tsx
  src/providers/TanstackQueryProvider.tsx
Labels: Feature_API

#88 delete:ForumPosts.tsx
  src/app/(home)/(posts)/_components/forum/ForumPosts.tsx
Labels: Delete

#89 feature: edit&posting api
  package-lock.json
  src/actions/revalidate.ts
  src/app/(home)/(upsert)/_components/FormSubmitButton.tsx
  src/app/(home)/(upsert)/_components/UpsertTheme.tsx
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormCategoryBox.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormContentArea.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormSubmitButton.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormTagInput.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormTitleInput.tsx
  src/app/(home)/(upsert)/_components/edit/editform/categorybox/ForumCategoryDropDown.tsx
  src/app/(home)/(upsert)/_components/edit/editform/categorybox/PostingCategory.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormCategoryBox.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormContentArea.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormSubmitButton.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormTagInput.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormTitleInput.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/categorybox/ForumCategoryDropDown.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/categorybox/PostingCategory.tsx
  src/app/(home)/(upsert)/edit/[id]/page.tsx
  src/app/api/posting/index.ts
  src/app/api/upsert/edit/[id]/route.ts
  src/app/api/upsert/posting/route.ts
  src/app/layout.tsx
  src/constants/posting.ts
  src/constants/upsert.api.ts
  src/constants/upsert.ts
  src/types/upsert.ts
Labels: Feature_API

#93 feature: context userInfo 추가, google-recaptcha 구현
  package-lock.json
  package.json
  src/app/(home)/(auth)/_components/SignupForm.tsx
  src/app/api/auth/login/route.ts
  src/app/api/auth/signup/route.ts
  src/context/auth.context.tsx
  src/middleware.ts
Labels: Feature_API, Extra

#95 Feature: mypage api
  src/app/(home)/(profile)/_components/MyActivities.tsx
  src/app/(home)/(profile)/_components/ProfileContent.tsx
  src/app/(home)/(profile)/_components/ProfileSetting.tsx
  src/app/(home)/(profile)/_components/ProfileSidebar.tsx
  src/app/(home)/(profile)/_components/myactivities/BookmarksList.tsx
  src/app/(home)/(profile)/_components/myactivities/CommentCard.tsx
  src/app/(home)/(profile)/_components/myactivities/LikesList.tsx
  src/app/(home)/(profile)/_components/myactivities/MyActivitiesHeader.tsx
  src/app/(home)/(profile)/_components/myactivities/MyPostsList.tsx
  src/app/(home)/(profile)/_components/myactivities/PostCard.tsx
  src/app/(home)/(profile)/_components/setting/EditableField.tsx
  src/app/(home)/(profile)/layout.tsx
  src/app/api/profile/bookmarkscomments/route.ts
  src/app/api/profile/bookmarksposts/route.ts
  src/app/api/profile/index.ts
  src/app/api/profile/likescomments/route.ts
  src/app/api/profile/likesposts/route.ts
  src/app/api/profile/profileauth/route.ts
  src/hooks/useBookmarks.ts
  src/hooks/useLikes.ts
Labels: Feature_API

#98 feature: tallwind
  public/fonts/Pretendard-Bold.ttf
  public/fonts/Pretendard-Medium.ttf
  public/fonts/Pretendard-Regular.ttf
  public/fonts/index.ts
  src/app/globals.css
  src/app/layout.tsx
  tailwind.config.ts
Labels: Chore

#100 fix: Tailwind Inconsistent Letter Spacing Units
  tailwind.config.ts
Labels: Chore, fix

#101 Style/header
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/assets/images/Logo.tsx
  src/components/header/Header.tsx
  src/components/header/NavLinks.tsx
  src/components/header/SearchBar.tsx
  src/components/header/UserMenu.tsx
  src/types/header/headerTypes.ts
Labels: Styling

#102 feature: markdown editor custom image button api
  src/app/(home)/(upsert)/_components/CustomMDEditor.tsx
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormContentArea.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormTagInput.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormTitleInput.tsx
  src/app/(home)/(upsert)/_components/edit/editform/categorybox/ForumCategoryDropDown.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormContentArea.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormTagInput.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormTitleInput.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/categorybox/ForumCategoryDropDown.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/categorybox/PostingCategory.tsx
  src/app/api/upsert/image/route.ts
  src/app/globals.css
  src/assets/images/upsert_image/BackArrowIcon.tsx
  src/assets/images/upsert_image/markdown/ImageIcon.tsx
  src/constants/upsert.ts
Labels: Feature_API

#104 feature: markdown image dragndrop api
  src/actions/revalidate.ts
  src/app/(home)/(upsert)/_components/CustomMDEditor.tsx
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/api/upsert/image/route.ts
  src/app/globals.css
  src/constants/upsert.ts
  src/types/upsert.ts
Labels: Feature_API

#105 Feature/qna posts api
  package-lock.json
  package.json
  src/app/(home)/(posts)/_components/qna/PopularQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/PostQnaButton.tsx
  src/app/(home)/(posts)/_components/qna/QnaImageSwiper.tsx
  src/app/(home)/(posts)/_components/qna/ResentQnaPosts.tsx
  src/app/(home)/(posts)/qna/page.tsx
  src/app/api/posts/forum/route.ts
  src/app/api/posts/qna/[status]/route.ts
  src/hooks/qna/useFetchQnaPosts.ts
  src/types/posts/qnaTypes.ts
  src/types/supabase.ts
Labels: Feature_API

#107 feature: upsert thumbnail UI
  src/app/(home)/(upsert)/_components/ThumbNailBox.tsx
  src/app/(home)/(upsert)/_components/UpsertTheme.tsx
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormCategoryBox.tsx
  src/app/(home)/(upsert)/_components/edit/editform/categorybox/PostingCategory.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormCategoryBox.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormContentArea.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormTitleInput.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/PostingCategoryBox.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/categorybox/ForumCategoryDropDown.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/categorybox/PostingCategory.tsx
  src/constants/upsert.ts
  src/store/postingCategoryStore.ts
Labels: Feature_UI

#111 feature: upsert thumbnail api
  src/app/(home)/(upsert)/_components/ThumbNailBox.tsx
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/api/upsert/edit/[id]/route.ts
  src/app/api/upsert/posting/route.ts
  src/app/api/upsert/thumbnail/route.ts
Labels: Feature_API

#115 fix: form validation bug
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/constants/upsert.ts
Labels: fix

#117 Feature/optimistic update
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/app/(home)/page.tsx
  src/app/api/common/bookmark/route.ts
  src/app/layout.tsx
  src/assets/images/bookmark/FilledBookmark.tsx
  src/assets/images/bookmark/UnfilledBookmark.tsx
  src/assets/images/header/Logo.tsx
  src/assets/images/header/SearchButton.tsx
  src/assets/images/like/filled_like.tsx
  src/assets/images/like/unfilled_like.tsx
  src/components/BookmarkButton.tsx
  src/components/header/Header.tsx
  src/components/header/SearchBar.tsx
  src/hooks/bookmark/useBookmark.ts
  src/providers/BookmarkProvider.tsx
  src/types/buttons/bookmark.tsx
Labels: Feature_API

#119 feature: add assets
  src/assets/images/auth/Github.tsx
  src/assets/images/auth/Google.tsx
  src/assets/images/auth/Kakao.tsx
  src/assets/images/common/BlueCheck.tsx
  src/assets/images/common/CarouselLeft.tsx
  src/assets/images/common/CarouselLeftHover.tsx
  src/assets/images/common/CarouselRight.tsx
  src/assets/images/common/CarouselRightHover.tsx
  src/assets/images/common/CommentBubble.tsx
  src/assets/images/common/CommentHide.tsx
  src/assets/images/common/Down.tsx
  src/assets/images/common/GoToTop.tsx
  src/assets/images/common/Left.tsx
  src/assets/images/common/Reset.tsx
  src/assets/images/common/Right.tsx
  src/assets/images/common/RightTriangle.tsx
  src/assets/images/common/Share.tsx
  src/assets/images/common/SortSetting.tsx
  src/assets/images/common/Up.tsx
  src/assets/images/common/WriteButton.tsx
  src/assets/images/common/Writer.tsx
  src/assets/images/common/X.tsx
  src/assets/images/common/kebab.tsx
Labels: Chore, Feature_UI

#121 Feature/optimistic likes
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/app/api/common/like/route.ts
  src/app/layout.tsx
  src/assets/images/like/FilledLike.tsx
  src/assets/images/like/UnfilledLike.tsx
  src/components/common/BookmarkButton.tsx
  src/components/common/LikeButton.tsx
  src/hooks/like/useLike.ts
  src/providers/LikeProvider.tsx
  src/types/buttons/bookmark.ts
  src/types/buttons/like.ts
Labels: Feature_API

#122 feature: Search UI
  src/app/(home)/(search)/_components/Search.tsx
  src/app/(home)/(search)/_components/SearchPostCard.tsx
  src/app/(home)/(search)/search/page.tsx
Labels: Feature_UI

#123 feature: qna detail page UI
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnacomments/AnswerComments.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnacomments/ButtonBox.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnacomments/QuestionComments.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnacomments/ReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/PostingQnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QnaAnswers.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QnaQuestion.tsx
  src/app/(home)/(posts)/qna/[id]/page.tsx
  src/app/api/posts/qnadetail/[id]/route.ts
  src/types/posts/qnaDetailTypes.ts
Labels: Feature_UI

#124 feature: archvie ui
  src/app/(home)/(posts)/_components/archive/PopularQnaSwiper.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/app/(home)/(posts)/archive/page.tsx
  src/app/(home)/(posts)/archiving/page.tsx
  src/app/api/posts/archive/route.ts
  src/components/header/NavLinks.tsx
  src/types/posts/archiveTypes.ts
Labels: Feature_UI

#125 Feature/archive posts api
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/archive/PopularArchiveSwiper.tsx
  src/app/(home)/(posts)/_components/archive/PopularQnaSwiper.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/app/(home)/(posts)/archive/page.tsx
  src/app/(home)/_components/PostsLink.tsx
  src/app/api/posts/archive/route.ts
  src/components/header/NavLinks.tsx
  src/hooks/archive/useFetchArchivePosts.ts
  src/types/posts/archiveTypes.ts
Labels: Feature_API

#126 Feature: search api
  src/app/(home)/(search)/_components/Search.tsx
  src/app/(home)/(search)/_components/SearchFilter.tsx
  src/app/(home)/(search)/_components/SearchPostCard.tsx
  src/app/api/search/index.ts
  src/app/api/search/route.ts
  src/components/header/SearchBar.tsx
Labels: Feature_API

#127 feature/OAuth: 소셜로그인 기능 구현
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(auth)/_components/NicknameCheck .tsx
  src/app/(home)/(auth)/_components/OAuthButtons.tsx
  src/app/(home)/(auth)/_components/OAuthNicknameModal.tsx
  src/app/(home)/(auth)/_components/OAuthNicknameModalWrapper.tsx
  src/app/(home)/(auth)/_components/PasswordFields.tsx
  src/app/(home)/(auth)/_components/SignupForm.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/app/api/auth/me/route.ts
  src/app/api/auth/signup/route.ts
  src/app/api/auth/update-nickname/route.ts
  src/context/auth.context.tsx
  src/hooks/useOAuthLogin.ts
  src/middleware.ts
  src/types/supabase.ts
Labels: Feature_API

#129 fix:like count button
  src/app/api/common/like/like-count/route.ts
  src/app/api/common/like/like/route.ts
  src/components/common/BookmarkButton.tsx
  src/components/common/LikeButton.tsx
  src/providers/LikeProvider.tsx
Labels: Feature_API, fix
