Repository final-semicolon/div, pull requests merged in 2024-08, with the labels that each got.

#132 update: ArchiveDetail UI
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
Labels: Feature_UI

#133 style : mypage content and setting
  src/app/(home)/(profile)/_components/ProfileContent.tsx
  src/app/(home)/(profile)/_components/ProfileSetting.tsx
  src/app/(home)/(profile)/_components/ProfileSidebar.tsx
  src/app/(home)/(profile)/_components/setting/InfoModal.tsx
  src/app/(home)/layout.tsx
  src/app/globals.css
  src/assets/images/bookmark/UnfilledBookmark.tsx
  src/assets/images/common/EditIcon.tsx
  src/assets/images/common/Right.tsx
  src/assets/images/like/UnfilledLike.tsx
Labels: Styling

#135 fix: error fixed
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/app/(home)/(posts)/_components/qna/ResentQnaPosts.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnacomments/AnswerReplies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnacomments/QuestionReplies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QnaQuestion.tsx
  src/app/(home)/layout.tsx
  src/app/globals.css
  src/assets/images/like/UnfilledLike.tsx
Labels: fix

#137 Style/archive posts style
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/archive/PopularArchiveSwiper.tsx
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/app/(home)/(posts)/_components/qna/PostQnaButton.tsx
  src/app/(home)/(posts)/_components/qna/QnaImageSwiper.tsx
  src/app/(home)/(posts)/_components/qna/ResentQnaPosts.tsx
  src/app/(home)/(posts)/archive/page.tsx
  src/app/api/posts/archive/route.ts
  src/assets/images/archive/ArchiveBannerOne.svg
  src/assets/images/archive/ArchiveBannerTwo.svg
  src/components/common/BookmarkButton.tsx
  src/types/posts/archiveTypes.ts
Labels: Styling

#138 feature: archivepost link
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/archive/PopularArchiveSwiper.tsx
Labels: Feature_UI

#141 Style/mypage
  src/app/(home)/(profile)/_components/MyActivities.tsx
  src/app/(home)/(profile)/_components/ProfileContent.tsx
  src/app/(home)/(profile)/_components/ProfileSetting.tsx
  src/app/(home)/(profile)/_components/ProfileSidebar.tsx
  src/app/(home)/(profile)/_components/myactivities/BookmarksList.tsx
  src/app/(home)/(profile)/_components/myactivities/LikesList.tsx
  src/app/(home)/(profile)/_components/myactivities/MyActivitiesHeader.tsx
  src/app/(home)/(profile)/_components/myactivities/MyPostsList.tsx
  src/app/(home)/(profile)/_components/myactivities/common/CommentCard.tsx
  src/app/(home)/(profile)/_components/myactivities/common/CustomSelect .tsx
  src/app/(home)/(profile)/_components/myactivities/common/FilterControls.tsx
  src/app/(home)/(profile)/_components/myactivities/common/MyActivitiesPagination.tsx
  src/app/(home)/(profile)/_components/myactivities/common/PostCard.tsx
  src/app/(home)/(profile)/_components/setting/GithubUrlModal.tsx
  src/app/(home)/(profile)/_components/setting/InfoModal.tsx
  src/app/(home)/(profile)/_components/setting/NicknameModal.tsx
  src/app/(home)/(profile)/layout.tsx
  src/app/(home)/(profile)/profile/page.tsx
  src/app/globals.css
  src/assets/images/common/Check.tsx
  src/assets/images/common/Down.tsx
  src/assets/images/common/SortSetting.tsx
  src/assets/images/common/VectorImageIcon.tsx
  src/assets/images/common/X.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/Modal.tsx
  tailwind.config.ts
Labels: Styling

#143 feature/library: api 구현 및 기능 추가
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveInputComment.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReplyInput.tsx
  src/app/(home)/(posts)/_components/archive-detail/PaginationButton.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/app/api/posts/archive-detail/[id]/route.ts
  src/app/api/posts/archive-detail/archive-comments/[id]/route.ts
  src/app/api/posts/archive-detail/archive-reply/[id]/route.ts
  src/assets/images/bookmark/FilledBookmark.tsx
  src/assets/images/header/SearchButton.tsx
  src/assets/images/upsert_image/BackArrowIcon.tsx
  src/types/posts/archiveDetailTypes.ts
Labels: Feature_API

#145 fix:kebab name
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
Labels: fix

#146 fix/kebab
  src/assets/images/common/Kebab.tsx
Labels: fix

#147 fix/kebab
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
  src/app/(home)/(posts)/_components/forum-detail/ForumComments.tsx
  src/app/(home)/(posts)/_components/forum-detail/ForumDetailPost.tsx
  src/app/(home)/(posts)/_components/forum-detail/ForumReply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/AnswerKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QuestionKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QuestionReplyKebobBtn.tsx
  src/assets/images/common/KebabButton.tsx
Labels: fix

#148 Fix/kebab
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/forum-detail/ForumComments.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/AnswerReplytKebobBtn.tsx
  src/app/(home)/_components/TodayQna.tsx
Labels: fix

#154 fix: forum
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
Labels: fix

#156 fix: archive
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/archive/PopularArchiveSwiper.tsx
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/components/common/BookmarkButton.tsx
  src/types/posts/forumTypes.ts
Labels: fix

#158 fix: qna datail api
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/AnswerKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/PostingQnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QnaAnswers.tsx
  src/app/(home)/(upsert)/_components/ThumbNailBox.tsx
Labels: fix

#159 feature/library:
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveInputComment.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReplyInput.tsx
  src/app/(home)/(posts)/_components/archive-detail/BackClick.tsx
  src/app/(home)/(posts)/_components/archive-detail/PaginationButton.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/app/api/posts/archive-detail/[id]/route.ts
  src/app/api/posts/archive-detail/archive-comments/[id]/route.ts
  src/app/api/posts/archive-detail/archive-reply/[id]/route.ts
  src/types/posts/archiveDetailTypes.ts
Labels: fix

#164 fix : mypage
  src/app/(home)/(profile)/_components/myactivities/BookmarksList.tsx
  src/app/(home)/(profile)/_components/myactivities/LikesList.tsx
  src/app/(home)/(profile)/_components/myactivities/MyPostsList.tsx
  src/app/(home)/(profile)/_components/myactivities/common/CommentCard.tsx
  src/app/(home)/(profile)/_components/myactivities/common/FilterControls.tsx
  src/app/(home)/(search)/_components/Search.tsx
  src/app/(home)/(search)/_components/SearchFilter.tsx
  src/app/(home)/(search)/_components/SearchPostCard.tsx
  src/app/api/profile/bookmarkscomments/route.ts
  src/app/api/profile/bookmarksposts/route.ts
  src/app/api/profile/likescomments/route.ts
  src/app/api/profile/likesposts/route.ts
  src/app/api/profile/mycomments/route.ts
  src/app/api/profile/myposts/route.ts
  src/app/api/search/route.ts
  src/assets/images/common/VectorImageIcon.tsx
  src/types/profile/profileType.ts
  src/utils/combineItems.ts
Labels: fix

#168 [MERGE]
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
  src/app/(home)/(profile)/_components/ProfileContent.tsx
  src/app/(home)/(profile)/_components/ProfileSetting.tsx
  src/app/(home)/(profile)/_components/myactivities/BookmarksList.tsx
  src/app/(home)/(profile)/_components/myactivities/MyPostsList.tsx
  src/app/(home)/(search)/_components/Search.tsx
  src/app/api/auth/login/route.ts
  src/app/api/common/bookmark/route.ts
  src/app/api/common/like/like/route.ts
  src/app/api/posts/archive-detail/archive-comments/[id]/route.ts
  src/app/api/posts/archive/route.ts
  src/app/api/posts/forum-detail/[id]/route.ts
  src/app/api/posts/forum-detail/forum-comments/[id]/route.ts
  src/app/api/posts/forum/route.ts
  src/app/api/posts/qna-detail/comment/[id]/route.ts
  src/app/api/posts/qna-detail/qna-post-reply/[id]/route.ts
  src/app/api/posts/qna/[status]/route.ts
  src/app/api/profile/profileauth/route.ts
  src/components/common/BookmarkButton.tsx
  src/components/common/LikeButton.tsx
  src/context/auth.context.tsx
  src/hooks/useOAuthLogin.ts
  src/providers/BookmarkProvider.tsx
  src/providers/LikeProvider.tsx
  src/utils/imageUpload.ts
Labels: Chore

#169 fix: qna post delete bug
  src/actions/revalidatePostTag.ts
  src/app/(home)/(posts)/qna/[id]/_components/qnacomments/AnswerReplies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/AnswerKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/AnswerReplytKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/PostingAnswerModal.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QnaQuestion.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QuestionKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qnapost/QuestionReplyKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/page.tsx
  src/app/api/posts/qna-detail/[id]/route.ts
  src/app/api/posts/qna-detail/comment/[id]/route.ts
  src/app/api/posts/qna-detail/qna-post-reply/[id]/route.ts
  src/app/api/posts/qna-detail/qna-reply/[id]/route.ts
  src/constants/upsert.api.ts
Labels: fix

#170 Feature/library
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(auth)/_components/SignupForm.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/app/api/posts/archive-detail/[id]/route.ts
  src/context/auth.context.tsx
Labels: Chore, Styling, fix

#173 fix: qna
  src/app/(home)/(posts)/_components/qna/PopularQnaPosts.tsx
Labels: fix

#172 fix: 라이브러리 삭제 api 수정
  src/app/api/posts/archive-detail/[id]/route.ts
Labels: fix

#171 Chore/svg waening
  src/app/(home)/(profile)/_components/myactivities/BookmarksList.tsx
  src/app/(home)/(profile)/_components/myactivities/common/CommentCard.tsx
  src/app/(home)/(profile)/_components/myactivities/common/PostCard.tsx
  src/app/(home)/(profile)/_components/setting/InfoModal.tsx
  src/app/(home)/_components/BestForum.tsx
  src/assets/images/auth/Github.tsx
  src/assets/images/auth/Kakao.tsx
  src/assets/images/bookmark/UnfilledBookmark.tsx
  src/assets/images/common/BlueCheck.tsx
  src/assets/images/common/CarouselLeft.tsx
  src/assets/images/common/CarouselLeftHover.tsx
  src/assets/images/common/CarouselRight.tsx
  src/assets/images/common/CarouselRightHover.tsx
  src/assets/images/common/GoToTop.tsx
  src/assets/images/common/GoToTopHover.tsx
  src/assets/images/common/Left.tsx
  src/assets/images/common/Reset.tsx
  src/assets/images/common/Share.tsx
  src/assets/images/common/Up.tsx
  src/assets/images/common/WriteButton.tsx
  src/assets/images/forum/ForumCategoryIcon.tsx
  src/assets/images/forum/WriteButton.tsx
  src/assets/images/main-page_image/Pc.tsx
  src/assets/images/main-page_image/Star.tsx
  src/assets/images/main-page_image/qnaicom/Cap.tsx
  src/assets/images/qna/GradCap.tsx
  src/assets/images/qna/LeftButton.tsx
  src/assets/images/qna/RightButton.tsx
  src/assets/images/qna/SelectAnswer.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/Modal.tsx
  src/utils/imageUpload.ts
Labels: Chore, fix

#175 fix : BestForum & InfoModal
  src/app/(home)/(profile)/_components/setting/InfoModal.tsx
  src/app/(home)/_components/BestForum.tsx
Labels: fix

#188 Chore/separate qna detail components
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/confirm-modal/PostingAnswerModal.tsx
  src/app/(home)/(posts)/qna/[id]/_components/confirm-modal/PostingConfirmModal.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/AnswerKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/AnswerReplytKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/QuestionKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/QuestionReplyKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReplies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/QuestionReplies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/QuestionReply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/QuestionReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingQnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswers.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaQuestion.tsx
Labels: Chore

#189 feature: tag select input UI
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormTagInput.tsx
  src/components/common/SelectTagInput.tsx
  src/constants/tags.ts
  src/types/tag.ts
Labels: Feature_UI

#196 Feature/withdraw
  src/app/(home)/(profile)/_components/setting/DeleteAccountButton.tsx
  src/app/(home)/(profile)/profile/page.tsx
  src/app/api/auth/delete/route.ts
  src/context/auth.context.tsx
  src/supabase/admin.ts
Labels: Feature_API

#198 feature: 아카이브 디폴트 이미지 적용
  public/images/archive/default_thumbnail.webp
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/archive/PopularArchiveSwiper.tsx
Labels: Feature_UI

#200 feature: 무한스크롤 마지막 표시 ui
  src/components/common/EndOfData.tsx
Labels: Feature_UI

#201 feature: tag select input api
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswers.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaQuestion.tsx
  src/app/(home)/(posts)/qna/[id]/page.tsx
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormTagInput.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormTagInput.tsx
  src/app/(home)/(upsert)/edit/[id]/page.tsx
  src/app/api/posts/qna-detail/[id]/route.ts
  src/app/api/posts/qna-detail/comment/[id]/route.ts
  src/app/api/upsert/edit/[id]/route.ts
  src/app/api/upsert/tags/[id]/route.ts
  src/components/common/SelectTagInput.tsx
  src/components/common/TagBlock.tsx
  src/constants/tags.ts
  src/types/posts/qnaDetailTypes.ts
  src/types/supabase.ts
  src/types/upsert.ts
Labels: Feature_API

#203 Feature/accountconnetion
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(auth)/_components/OAuthLoginStatus.tsx
  src/app/(home)/(profile)/_components/ProfileSidebar.tsx
  src/app/(home)/(profile)/profile/page.tsx
  src/app/(home)/page.tsx
  src/assets/images/auth/Div.tsx
  src/assets/images/auth/Google.tsx
  src/components/header/Header.tsx
  src/components/header/UserMenu.tsx
  src/types/header/headerTypes.ts
Labels: Feature_UI, Feature_API

#205 feature: forumposts inf scroll end noti
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
Labels: Feature_UI

#208 Update/my page profile
  src/app/(home)/(auth)/_components/OAuthLoginStatus.tsx
  src/app/(home)/(profile)/_components/AtherProfile.tsx
  src/app/(home)/(profile)/_components/ProfileSetting.tsx
  src/app/(home)/(profile)/_components/ProfileSidebar.tsx
  src/app/(home)/(profile)/_components/setting/CheckCurrentPassword.tsx
  src/app/(home)/(profile)/_components/setting/DeleteAccountButton.tsx
  src/app/(home)/(profile)/_components/setting/EditableField.tsx
  src/app/(home)/(profile)/_components/setting/InfoModal.tsx
  src/app/(home)/(profile)/_components/setting/NewPassword.tsx
  src/app/(home)/(profile)/_components/setting/NicknameModal.tsx
  src/app/(home)/(profile)/_components/setting/PasswordModal.tsx
  src/app/(home)/(profile)/profile/[id]/page.tsx
  src/app/(home)/(profile)/profile/page.tsx
  src/app/(home)/page.tsx
  src/app/api/profile/profileauth/route.ts
  src/app/api/profile/reset-password/route.ts
  src/app/api/profile/verify-password/route.ts
  src/assets/images/auth/Div40X40.tsx
  src/assets/images/auth/Github40X40.tsx
  src/assets/images/auth/Google40X40.tsx
  src/assets/images/auth/Kakao40X40.tsx
  src/assets/images/common/ReverseExclamation.tsx
  src/assets/images/common/X.tsx
  src/components/modal/ConfirmModal.tsx
  src/components/modal/Modal.tsx
Labels: Feature_UI, Feature_API

#209 feature: filter slangs
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/app/(home)/(posts)/_components/qna/PopularQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/ResentQnaPosts.tsx
  src/app/(home)/_components/BestForum.tsx
  src/components/common/MarkdownCut.tsx
  src/utils/markdownCut.ts
  src/utils/slangs.ts
Labels: Feature_API

#212 fix: error
  src/app/(home)/_components/BestForum.tsx
Labels: Feature_UI

#213 feature:filterslang
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/utils/markdownCut.ts
Labels: Feature_UI

#215 Update/libary
  src/app/(home)/(auth)/_components/CheckboxGroup.tsx
  src/app/(home)/(auth)/_components/EmailCheck.tsx
  src/app/(home)/(auth)/_components/InputField.tsx
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(auth)/_components/LoginInputField.tsx
  src/app/(home)/(auth)/_components/NicknameCheck .tsx
  src/app/(home)/(auth)/_components/OAuthNicknameModal.tsx
  src/app/(home)/(auth)/_components/PasswordFields.tsx
  src/app/(home)/(auth)/_components/SigninInputField.tsx
  src/app/(home)/(auth)/_components/SignupButton.tsx
  src/app/(home)/(auth)/_components/SignupForm.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveInputComment.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReplyInput.tsx
  src/app/(home)/(posts)/_components/archive-detail/PaginationButton.tsx
  src/app/(home)/(posts)/_components/archive-detail/ReplyPageButton.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/app/api/auth/check-email/route.ts
  src/app/api/auth/check-nickname/route.ts
  src/app/api/auth/login/route.ts
  src/app/api/posts/archive-detail/[id]/route.ts
  src/app/api/posts/archive-detail/archive-comments/[id]/route.ts
  src/app/api/posts/archive-detail/archive-reply/[id]/route.ts
  src/supabase/middleware.ts
  src/types/posts/archiveDetailTypes.ts
Labels: MiddleWare, Styling, fix

#221 fix: button styling
  src/components/common/SortDropdownGrey.tsx
Labels: fix

#224 Fix/libary
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/app/(home)/(posts)/forum/[id]/page.tsx
  src/app/api/posts/archive-detail/[id]/route.ts
  src/types/posts/archiveDetailTypes.ts
Labels: fix

#228 feature:favicon
  src/app/favicon.ico
Labels: Chore

#233 Update/libary 날짜표기 변경
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(terms)/legal/privacy/page.tsx
  src/app/(home)/(terms)/legal/terms/page.tsx
Labels: fix

#237 fix: upsert submit logic
  package-lock.json
  package.json
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(upsert)/_components/FormContentArea.tsx
  src/app/(home)/(upsert)/_components/FormSubmitButton.tsx
  src/app/(home)/(upsert)/_components/FormTitleInput.tsx
  src/app/(home)/(upsert)/_components/ThumbNailBox.tsx
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/edit/editform/FormContentArea.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/FormTitleInput.tsx
  src/app/(home)/(upsert)/_utils/thumbnail.ts
  src/app/(home)/(upsert)/edit/[id]/page.tsx
  src/app/api/upsert/thumbnail/route.ts
  src/components/common/CustomMDEditor.tsx
  src/constants/upsert.ts
  src/types/upsert.ts
Labels: fix

#238 Fix : profile info logout
  src/app/(home)/(profile)/_components/ProfileSetting.tsx
  src/app/(home)/(profile)/_components/ProfileSidebar.tsx
  src/context/auth.context.tsx
Labels: fix

#240 fix: search Like button isn’t working
  src/app/(home)/(profile)/_components/setting/CheckCurrentPassword.tsx
  src/app/(home)/(search)/_components/Search.tsx
  src/app/(home)/(search)/_components/SearchPostCard.tsx
Labels: fix

#246 fix:toastify
  src/app/layout.tsx
  src/providers/Providers.tsx
Labels: fix

#248 fix: toastify
  src/providers/Providers.tsx
Labels: fix

#249 Refactor/files
  src/app/(home)/(auth)/_components/SignupForm.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/forum-detail/ForumDetailPost.tsx
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/app/(home)/(profile)/_components/myactivities/BookmarksList.tsx
  src/app/(home)/(profile)/_components/myactivities/LikesList.tsx
  src/app/(home)/(search)/search/page.tsx
  src/app/(home)/_components/BestForum.tsx
  src/app/(home)/page.tsx
  src/components/common/Bookmark.tsx
  src/components/common/TopButton.tsx
  src/context/index.ts
  src/hooks/common/useBookmarks.ts
  src/hooks/common/useLikes.ts
  src/hooks/common/useOAuthLogin.ts
  src/hooks/index.ts
  src/store/index.ts
  src/utils/handleLinkCopy.ts
  src/utils/handleRinkCopy.ts
  src/utils/index.ts
Labels: Refactor

#254 Style/fix style
  src/app/(home)/(posts)/_components/forum/BestForumPosts.tsx
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/app/(home)/(posts)/forum/page.tsx
  src/app/(home)/layout.tsx
  src/app/api/posts/forum/all-forum/route.ts
  src/assets/images/bookmark/UnfilledBookmark.tsx
  src/assets/images/common/CommentBubble.tsx
  src/assets/images/common/GoToTop.tsx
  src/assets/images/common/GoToTopHover.tsx
  src/assets/images/common/Share.tsx
  src/assets/images/forum/Info.tsx
  src/assets/images/forum/King.tsx
  src/assets/images/forum/Tooltip.tsx
  src/assets/images/like/UnfilledLike.tsx
  src/components/common/LikeButton.tsx
  src/components/common/SortDropdownGrey.tsx
  src/hooks/forum/useFetchTopLikedPosts.ts
Labels: Feature_UI, fix

#256 fix: upsertpage missing
  src/app/(home)/(upsert)/_components/FormContentArea.tsx
  src/app/(home)/(upsert)/_components/FormSubmitButton.tsx
  src/app/(home)/(upsert)/_components/FormTitleInput.tsx
  src/app/(home)/(upsert)/_components/ThumbNailBox.tsx
  src/app/(home)/(upsert)/_components/UpsertTheme.tsx
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/edit/editform/categorybox/PostingCategory.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/PostingCategoryBox.tsx
  src/app/globals.css
  src/assets/images/upsert_image/Twinkle.tsx
  src/components/common/CustomMDEditor.tsx
  src/components/common/SelectTagInput.tsx
  src/constants/upsert.ts
  src/store/postingCategoryStore.ts
  src/store/upsertValidationStore.ts
  tailwind.config.ts
Labels: fix

#259 fix: qna style
  public/images/qna/QnaPostsBanner.jpg
  src/app/(home)/(posts)/_components/qna/PopularQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/ResentQnaPosts.tsx
  src/app/(home)/(posts)/qna/page.tsx
  src/app/(home)/_components/QnaBackground.tsx
  src/app/(home)/layout.tsx
  src/app/api/posts/qna/[status]/route.ts
  src/components/header/Header.tsx
  src/types/posts/qnaTypes.ts
Labels: Feature_UI, Feature_API, fix

#261 fix: header style
  src/assets/images/header/Logo.tsx
  src/assets/images/header/X.tsx
  src/components/header/Header.tsx
  src/components/header/NavLinks.tsx
  src/components/header/SearchBar.tsx
  src/components/header/UserMenu.tsx
Labels: Feature_UI, fix

#262 fix: upsert thumbnail box
  package-lock.json
  package.json
  src/app/(home)/(upsert)/_components/ThumbNailBox.tsx
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/(home)/(upsert)/_components/posting/postingform/PostingCategoryBox.tsx
  src/app/globals.css
  src/assets/images/upsert_image/SadIcon.tsx
  src/components/common/SelectTagInput.tsx
Labels: fix

#264 fix: archive posts style
  public/images/archive/archive_banner_1.png
  public/images/archive/archive_banner_2.png
  public/images/archive/default_thumbnail.png
  public/images/archive/default_thumbnail.webp
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/archive/PopularArchiveSwiper.tsx
  src/app/(home)/(posts)/archive/page.tsx
  src/app/(home)/_components/ArchiveBackground.tsx
  src/app/(home)/_components/QnaBackground.tsx
  src/app/(home)/layout.tsx
  src/app/globals.css
  src/assets/images/archive/ArchiveBannerOne.svg
  src/assets/images/archive/ArchiveBannerTwo.svg
  src/components/header/UserMenu.tsx
  src/types/posts/archiveTypes.ts
Labels: Feature_UI, fix

#268 fix: qna detail page logic (add refetch in QnaAnswers infiniteQuery)
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswers.tsx
Labels: fix

#270 style: qna detail page
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/AnswerKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/AnswerReplytKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/QuestionKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/QuestionReplyKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/QuestionReply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/QuestionReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaQuestion.tsx
  src/app/globals.css
  src/components/modal/ConfirmModal.tsx
  src/constants/comment.ts
  src/constants/upsert.ts
  src/store/qnaDetailStore.ts
Labels: Styling

#267 feature: fonts
  .vscode/settings.json
  package-lock.json
  public/fonts/Pretendard-Bold.ttf
  public/fonts/Pretendard-Medium.ttf
  public/fonts/Pretendard-Regular.ttf
  public/images/index.ts
  src/app/(home)/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/assets/fonts/PretendardVariable.woff2
  src/assets/fonts/index.ts
  tailwind.config.ts
Labels: Feature_UI, fix

#277 Update/libary, Signup, Login
  package-lock.json
  package.json
  src/app/(home)/(auth)/_components/CheckboxGroup.tsx
  src/app/(home)/(auth)/_components/EmailCheck.tsx
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(auth)/_components/LoginInputField.tsx
  src/app/(home)/(auth)/_components/NicknameCheck .tsx
  src/app/(home)/(auth)/_components/OAuthButtons.tsx
  src/app/(home)/(auth)/_components/OAuthNicknameModal.tsx
  src/app/(home)/(auth)/_components/PasswordFields.tsx
  src/app/(home)/(auth)/_components/SigninInputField.tsx
  src/app/(home)/(auth)/_components/SignupButton.tsx
  src/app/(home)/(auth)/_components/SignupForm.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveInputComment.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReplyInput.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/app/api/auth/check-nickname/route.ts
  src/app/api/posts/forum-detail/forum-comments/index.ts
  src/assets/images/auth/CheckBox.tsx
  src/assets/images/auth/CheckError.tsx
  src/assets/images/auth/CheckVector.tsx
  src/assets/images/auth/RedI.tsx
  src/assets/images/auth/RedX.tsx
  src/assets/images/auth/UnCheckBox.tsx
  src/assets/images/auth/Vector.tsx
  src/assets/images/common/I.tsx
Labels: fix, Refactor

#282 Refactor/mypage profile
  src/app/(home)/(profile)/_components/AtherProfile.tsx
  src/app/(home)/(profile)/_components/ProfileContent.tsx
  src/app/(home)/(profile)/_components/ProfileSetting.tsx
  src/app/(home)/(profile)/_components/ProfileSidebar.tsx
  src/app/(home)/(profile)/_components/myactivities/MyPostsList.tsx
  src/app/(home)/(profile)/_components/setting/CheckCurrentPassword.tsx
  src/app/(home)/(profile)/_components/setting/GithubUrlModal.tsx
  src/app/(home)/(profile)/_components/setting/InfoModal.tsx
  src/app/(home)/(profile)/_components/setting/NewPassword.tsx
  src/app/(home)/(profile)/_components/setting/NicknameModal.tsx
  src/app/(home)/(profile)/_components/setting/ProfileImage.tsx
  src/app/(home)/(profile)/_components/setting/SettingItem.tsx
  src/app/(home)/(profile)/_components/setting/SettingsList.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/CheckCurrentPassword.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/InfoModal.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/NewPassword.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/NicknameModal.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/PasswordInput.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/PasswordModal.tsx
  src/app/(home)/(profile)/layout.tsx
  src/app/(home)/(profile)/profile/[id]/page.tsx
  src/app/(home)/(profile)/profile/page.tsx
  src/app/(home)/(profile)/profile/settings/page.tsx
  src/assets/images/common/Right24X24.tsx
  src/components/common/CapsLock.tsx
  src/components/modal/Modal.tsx
  src/constants/auth.ts
  src/hooks/common/useDebounce.ts
  src/hooks/common/useNicknameValidation.ts
  src/utils/profileStyles.ts
Labels: Refactor

#284 refactor: qna datail page kebob button
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/AnswerKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/AnswerReplytKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/KebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/QuestionKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/QuestionReplyKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReplies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/QuestionReplies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/QuestionReply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/QuestionReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaQuestion.tsx
  src/app/(home)/(posts)/qna/[id]/_hooks/useDeleteMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/useKebob.ts
  src/constants/confirmModal.ts
Labels: Refactor

#286 refactor/likes
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/app/api/common/like/new-like/route.ts
  src/app/api/posts/forum/route.ts
  src/components/common/NewLikeButton.tsx
  src/hooks/common/useDebounce.ts
  src/types/posts/forumTypes.ts
Labels: Refactor

#291 Refactor/qna posts
  package-lock.json
  package.json
  public/images/qna/QnaPostsBanner.webp
  src/app/(home)/(posts)/_components/qna/PopularQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/QnaImageSwiper.tsx
  src/app/(home)/(posts)/_components/qna/ResentQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/popular-qna/PopualrQnaPagination.tsx
  src/app/(home)/(posts)/_components/qna/popular-qna/PopularQnaPostItem.tsx
  src/app/(home)/(posts)/_components/qna/popular-qna/PopularQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/Pagination.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItem.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/ResentQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/StatusTabs.tsx
  src/app/(home)/(posts)/qna/page.tsx
  src/app/api/posts/index.ts
Labels: Refactor

#292 refactor:qna_posts
  src/app/(home)/(posts)/qna/page.tsx
Labels: Refactor

#295 refactor: archive_posts
  src/app/(home)/(posts)/_components/archive/ArchivePostCard.tsx
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/archive/Pagination.tsx
  src/app/(home)/(posts)/_components/archive/PopularArchiveSwiper.tsx
  src/app/(home)/(posts)/_components/archive/SectionHeader.tsx
  src/app/(home)/(posts)/_components/archive/SwiperNavigationButton.tsx
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/Pagination.tsx
  src/app/(home)/(posts)/archive/page.tsx
  src/app/(home)/(posts)/qna/page.tsx
  src/app/api/posts/forum/route.ts
  src/hooks/forum/useFetchForumPosts.ts
  src/types/posts/archiveTypes.ts
Labels: Refactor

#296 Fix/font
  src/app/layout.tsx
  src/assets/fonts/PretendardVariable.woff2
  src/assets/fonts/subset-PretendardVariable-Regular.ttf
  src/assets/fonts/subset-PretendardVariable-Regular.woff
  src/assets/fonts/subset-PretendardVariable-Regular.woff2
Labels: fix

#299 refactor: qna detail page reply
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReplies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/AnswerReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/QuestionReplies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/QuestionReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Replies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Reply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/ReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingQnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswers.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaQuestion.tsx
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useAddReplyMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useEditReplyMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useReply.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useReplyForm.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/useDeleteMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/useKebob.ts
  src/app/(home)/(posts)/qna/[id]/page.tsx
  src/app/api/posts/qna-detail/qna-post-reply/[id]/route.ts
  src/app/api/posts/qna-detail/qna-reply/[id]/route.ts
Labels: Refactor

#298 Refactor/forumposts
  components.json
  package-lock.json
  package.json
  src/app/(home)/(posts)/_components/forum/BestForumPosts.tsx
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/app/(home)/(posts)/_components/forum/PostCard.tsx
  src/app/(home)/(posts)/_components/forum/ScrollToTopButton.tsx
  src/app/(home)/(posts)/_components/forum/card/PostCard.tsx
  src/app/(home)/(posts)/_components/forum/card/PostHeader.tsx
  src/app/(home)/(posts)/_components/forum/card/PostTags.tsx
  src/app/(home)/(posts)/_components/forum/skeleton/BestForumSkeleton.tsx
  src/app/(home)/(posts)/_components/forum/skeleton/PostCardSkeleton.tsx
  src/app/(home)/(posts)/forum/page.tsx
  src/app/api/posts/forum/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/components/ui/skeleton.tsx
  src/hooks/forum/useFetchForumPosts.ts
  src/lib/utils.ts
  src/types/posts/forumTypes.ts
  src/utils/markdownCut.ts
  tailwind.config.ts
Labels: Refactor

#302 Refactor/qna post
  src/app/(home)/(posts)/_components/forum/BestForumPosts.tsx
  src/app/(home)/(posts)/_components/qna/popular-qna/PopularQnaPostItem.tsx
  src/app/(home)/(posts)/_components/qna/popular-qna/PopularQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItem.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemSelected.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemWaiting.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/ResentQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/StatusTabs.tsx
  src/app/(home)/(posts)/_components/qna/skeleton/PopularQnaPostsSkeleton.tsx
  src/app/(home)/(posts)/_components/qna/skeleton/QnaPostItemSkeleton.tsx
  src/app/(home)/(posts)/qna/page.tsx
  src/app/api/posts/qna/[status]/route.ts
  src/assets/images/common/BlueCheck.tsx
  src/hooks/qna/useFetchQnaPosts.ts
  src/types/posts/qnaTypes.ts
Labels: Refactor

#304 refactor: header
  src/components/header/Header.tsx
  src/components/header/HeaderWrapper.tsx
  src/components/header/NavLinks.tsx
  src/components/header/UserMenu.tsx
Labels: Refactor

#306 refactor: archiveposts
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/archive/PopularArchiveSwiper.tsx
  src/app/(home)/(posts)/_components/archive/skeleton/ArchivePostCardSkeleton.tsx
  src/app/(home)/(posts)/_components/archive/skeleton/ArchivePostsSkeleton.tsx
  src/app/(home)/(posts)/_components/archive/skeleton/PopularArchiveSwiperSkeleton.tsx
  src/app/(home)/(posts)/_components/index.ts
Labels: Refactor

#307 fix: qna detail answers
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Replies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Reply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswers.tsx
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useAddReplyMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/useDeleteMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/useKebob.ts
  src/app/(home)/(posts)/qna/[id]/page.tsx
  src/app/api/posts/qna-detail/comment/[id]/route.ts
  src/app/api/posts/qna-detail/qna-reply/[id]/route.ts
  src/app/api/posts/qna-detail/question/[id]/route.ts
  src/components/common/ReplyPageBtn.tsx
  src/constants/alert.ts
  src/constants/upsert.api.ts
  src/store/qnaDetailStore.ts
Labels: fix

#310 Refactor: search page
  package-lock.json
  package.json
  src/app/(home)/(search)/_components/PostCountDisplay.tsx
  src/app/(home)/(search)/_components/Search.tsx
  src/app/(home)/(search)/_components/SearchFilter.tsx
  src/app/(home)/(search)/_components/SearchHistory.tsx
  src/app/(home)/(search)/_components/SearchPostCard.tsx
  src/app/(home)/layout.tsx
  src/app/api/search/route.ts
  src/app/globals.css
  src/assets/images/common/CommentBubble.tsx
  src/components/categoryfilter/CategoryButton.tsx
  src/components/categoryfilter/ContentFilters.tsx
  src/components/categoryfilter/PrimaryCategories.tsx
  src/components/categoryfilter/SortingFilters.tsx
  src/components/header/SearchBar.tsx
  src/hooks/common/useMediaQuery.ts
  src/types/search/SearchType.ts
Labels: Refactor

#313 Update/libary
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(auth)/_components/OAuthNicknameModal.tsx
  src/app/(home)/(auth)/_components/SignupButton.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveInputComment.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReplyInput.tsx
  src/app/(home)/(posts)/_components/archive-detail/ReplyPageButton.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/app/(home)/(posts)/forum/[id]/page.tsx
  src/app/api/posts/archive-detail/[id]/route.ts
  src/components/common/BackClick.tsx
  src/components/common/CommentPageButton.tsx
  src/components/common/ReplyPageBtn.tsx
Labels: Feature_UI

#315 Style/responsive header
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemWaiting.tsx
  src/app/(home)/layout.tsx
  src/app/globals.css
  src/assets/images/header/MobileHamburgerButton.tsx
  src/assets/images/header/MobileLogo.tsx
  src/assets/images/header/MobileSearchButton.tsx
  src/assets/images/header/MobileWriteButton.tsx
  src/components/header/Header.tsx
  src/components/header/NavLinks.tsx
  src/components/header/SearchBar.tsx
  src/components/header/UserMenu.tsx
  src/components/modal/HeaderModal.tsx
  src/components/modal/Modal.tsx
  src/types/header/headerTypes.ts
Labels: Feature_UI

#316 feature: qna detail sorting
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Replies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Reply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/ReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingQnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswers.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaQuestion.tsx
  src/app/(home)/(posts)/qna/[id]/_components/skeleton/QnaAnswerSkeleton.tsx
  src/app/(home)/(posts)/qna/[id]/_components/skeleton/QnaReplyFormSkeleton.tsx
  src/app/(home)/(posts)/qna/[id]/_components/skeleton/QnaReplySkeleton.tsx
  src/app/(home)/(posts)/qna/[id]/_hooks/useDeleteMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/useKebob.ts
  src/app/api/posts/qna-detail/comment/[id]/route.ts
  src/assets/images/bookmark/UnfilledBookmark.tsx
  src/assets/images/common/RightIconHover.tsx
  src/assets/images/common/Share.tsx
  src/assets/images/common/Top.tsx
  src/assets/images/common/TopHover.tsx
  src/assets/images/forum/Tooltip.tsx
  src/assets/images/like/UnfilledLike.tsx
  src/store/qnaDetailStore.ts
  src/types/supabase.ts
Labels: Feature_UI, Feature_API

#320 style: responsive forum Posts
  src/app/(home)/(posts)/_components/forum/CategoryTabs.tsx
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/app/(home)/(posts)/_components/forum/ScrollToTopButton.tsx
  src/app/(home)/(posts)/_components/forum/card/PostCard.tsx
  src/app/(home)/(posts)/_components/forum/card/PostHeader.tsx
  src/app/(home)/(posts)/_components/forum/card/PostTags.tsx
  src/app/(home)/(posts)/_components/forum/mobile/MobileWriteButton.tsx
  src/app/(home)/(posts)/forum/page.tsx
  src/app/(home)/layout.tsx
  src/app/globals.css
  src/assets/images/common/Down.tsx
  src/assets/images/common/GoToTop.tsx
  src/assets/images/common/GoToTopHover.tsx
  src/components/common/DraggableScroll.tsx
  src/components/common/NewLikeButton.tsx
  src/components/common/SortDropdownGrey.tsx
  src/components/header/Header.tsx
  src/components/header/NavLinks.tsx
  src/context/auth.context.tsx
  src/types/posts/forumTypes.ts
Labels: Feature_UI, Styling

#325 Style/responsive qna posts
  public/images/qna/MobileQnaBanner.webp
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/app/(home)/(posts)/_components/qna/banner/QnaBanner.tsx
  src/app/(home)/(posts)/_components/qna/popular-qna/PopualrQnaPagination.tsx
  src/app/(home)/(posts)/_components/qna/popular-qna/PopularQnaPostItem.tsx
  src/app/(home)/(posts)/_components/qna/popular-qna/PopularQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/Pagination.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemSelected.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemWaiting.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/ResentQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/StatusTabs.tsx
  src/app/(home)/(posts)/qna/page.tsx
  src/app/(home)/_components/QnaBackground.tsx
  src/app/api/posts/qna/[status]/route.ts
  src/assets/images/common/BlueCheck.tsx
  src/assets/images/like/FilledLike.tsx
  src/assets/images/qna/GradCap.tsx
  src/components/header/Header.tsx
  src/components/header/NavLinks.tsx
Labels: Feature_UI, Styling

#328 Refactor: search page
  src/app/(home)/(search)/_components/PostCountDisplay.tsx
  src/app/(home)/(search)/_components/Search.tsx
  src/app/(home)/(search)/_components/SearchFilter.tsx
  src/app/(home)/(search)/_components/SearchPostCard.tsx
  src/app/globals.css
  src/assets/images/common/Down.tsx
  src/assets/images/common/SortSetting.tsx
  src/assets/images/common/SortSetting20X20.tsx
  src/assets/images/header/SearchButton.tsx
  src/components/categoryfilter/CategoryButton.tsx
  src/components/categoryfilter/ForumToggle.tsx
  src/components/categoryfilter/PrimaryCategories.tsx
  src/components/categoryfilter/SortingFilters.tsx
  src/components/common/LikeButton.tsx
  src/components/common/OptionsResponsive.tsx
  src/components/header/SearchBar.tsx
  src/types/search/SearchType.ts
  tailwind.config.ts
Labels: Refactor

#336 feature/404
  src/app/not-found.tsx
Labels: Feature_UI

#337 Style/profile setting
  src/app/(home)/(auth)/_components/OAuthLoginStatus.tsx
  src/app/(home)/(profile)/_components/ProfileSetting.tsx
  src/app/(home)/(profile)/_components/ProfileSidebar.tsx
  src/app/(home)/(profile)/_components/SidebarResponsive/HaderMobile.tsx
  src/app/(home)/(profile)/_components/SidebarResponsive/SidebarDesktop.tsx
  src/app/(home)/(profile)/_components/SidebarResponsive/SidebarTablet.tsx
  src/app/(home)/(profile)/_components/setting/DeleteAccountButton.tsx
  src/app/(home)/(profile)/_components/setting/ProfileImage.tsx
  src/app/(home)/(profile)/_components/setting/SettingItem.tsx
  src/app/(home)/(profile)/_components/setting/SettingsList.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/InfoModal.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/NicknameModal.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/PasswordInput.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/PasswordModal.tsx
  src/app/(home)/(profile)/_components/setting/settingresponsive/InfoModalFlow.tsx
  src/app/(home)/(profile)/_components/setting/settingresponsive/NicknameModalFlow.tsx
  src/app/(home)/(profile)/_components/setting/settingresponsive/SettingDefaultFlow.tsx
  src/app/(home)/(profile)/_components/setting/settingresponsive/SettingMobileFlow.tsx
  src/app/(home)/(profile)/layout.tsx
  src/app/(home)/(profile)/profile/page.tsx
  src/assets/images/common/EditIcon.tsx
  src/components/modal/MobileModal.tsx
  src/hooks/common/useMediaQuery.ts
Labels: Styling

#339 Style/responsive qna detail page
  package-lock.json
  package.json
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/KebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/QuestionKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Replies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Reply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/ReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingQnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswers.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaQuestion.tsx
  src/app/(home)/(posts)/qna/[id]/_components/skeleton/QnaReplyFormSkeleton.tsx
  src/app/(home)/(posts)/qna/[id]/_components/skeleton/QnaReplySkeleton.tsx
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useAddReplyMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useEditReplyMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/useDeleteMutation.ts
  src/app/(home)/(upsert)/_components/FormTitleInput.tsx
  src/app/globals.css
  src/assets/images/qna/SelectAnswer.tsx
  src/assets/images/upsert_image/ImageIcon.tsx
  src/assets/images/upsert_image/SadIcon.tsx
  src/components/common/Chip.tsx
  src/components/common/LikeButton.tsx
  src/components/common/SelectTagInput.tsx
  src/components/common/Tag.tsx
  src/components/common/TagBlock.tsx
  tailwind.config.ts
Labels: Styling

#340 Style/responsive qna detail page
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaQuestion.tsx
Labels: fix

#343 style fix
  src/app/(home)/(posts)/_components/forum/card/PostCard.tsx
  src/app/(home)/(posts)/_components/qna/popular-qna/PopularQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemSelected.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemWaiting.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/ResentQnaPosts.tsx
  src/app/(home)/(posts)/_components/qna/skeleton/PopularQnaPostsSkeleton.tsx
  src/app/(home)/(posts)/_components/qna/skeleton/QnaPostItemSkeleton.tsx
  src/app/(home)/(posts)/_components/qna/skeleton/QnaPostsSkeleton.tsx
  src/app/(home)/layout.tsx
  src/app/api/posts/qna/[status]/route.ts
  src/components/common/SearchPadding.tsx
  src/components/header/Header.tsx
  src/components/header/HeaderWrapper.tsx
  src/hooks/qna/useFetchQnaPosts.ts
Labels: Styling

#344 [REFACTOR] fix header modal
  src/components/header/Header.tsx
  src/components/modal/HeaderModal.tsx
Labels: fix

#346 Fix/archiveskeleton
  src/app/(home)/(posts)/_components/archive/ArchivePostCard.tsx
  src/app/(home)/(posts)/_components/archive/ArchivePostCardMobile.tsx
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/archive/PopularArchiveSwiper.tsx
  src/app/(home)/(posts)/_components/archive/skeleton/ArchivePostCardSkeleton.tsx
  src/app/(home)/(posts)/_components/archive/skeleton/ArchivePostsSkeleton.tsx
  src/app/(home)/(posts)/_components/archive/skeleton/PopularArchiveSwiperSkeleton.tsx
  src/app/(home)/(posts)/_components/forum/card/PostTags.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemWaiting.tsx
  src/components/header/SearchBar.tsx
Labels: fix

#353 style: LibaryDetailPage
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(auth)/_components/OAuthNicknameModal.tsx
  src/app/(home)/(auth)/_components/SignupForm.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveInputComment.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReplyInput.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/assets/images/header/Logo.tsx
  src/components/common/CommentPageButton.tsx
Labels: Styling

#357 fix: qna detail page edit answer(mobile)
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswers.tsx
Labels: fix

#355 fix: categoryfiter x scroll
  src/app/(home)/(profile)/_components/SidebarResponsive/HaderMobile.tsx
  src/app/(home)/(profile)/_components/myactivities/BookmarksList.tsx
  src/app/(home)/(profile)/_components/myactivities/LikesList.tsx
  src/app/(home)/(profile)/_components/myactivities/MyPostsList.tsx
  src/app/(home)/(profile)/_components/myactivities/common/FilterControls.tsx
  src/app/(home)/(search)/_components/Search.tsx
  src/app/(home)/(search)/_components/SearchFilter.tsx
  src/app/globals.css
  src/components/categoryfilter/ForumToggle.tsx
  src/components/categoryfilter/PrimaryCategories.tsx
  src/components/header/SearchBar.tsx
  src/hooks/common/useMediaQuery.ts
  src/store/useProfiletopTabStore.ts
Labels: fix

#358 fix: qna answer url (get answer data)
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswers.tsx
Labels: fix

#361 fix: Hader error
  src/app/(home)/(profile)/_components/SidebarResponsive/HaderMobile.tsx
  src/app/(home)/(profile)/_components/myactivities/MyActivitiesHeader.tsx
  src/components/modal/HeaderModal.tsx
  src/store/useActiveTabStore.ts
  src/store/useProfiletopTabStore.ts
Labels: fix

#365 Fix/errors
  src/app/(home)/(posts)/_components/archive/ArchiveBanner.tsx
  src/app/(home)/(posts)/_components/archive/ArchivePostCard.tsx
  src/app/(home)/(posts)/_components/archive/ArchivePostCardMobile.tsx
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/archive/skeleton/ArchivePostsSkeleton.tsx
  src/app/(home)/(posts)/_components/forum-detail/ForumComments.tsx
  src/app/(home)/(posts)/_components/forum/BestForumPosts.tsx
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/app/(home)/(posts)/_components/forum/card/PostCard.tsx
  src/app/(home)/(posts)/_components/forum/card/PostHeader.tsx
  src/app/(home)/(posts)/_components/forum/mobile/MobileWriteButton.tsx
  src/app/(home)/(posts)/_components/qna/popular-qna/PopularQnaPostItem.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemSelected.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemWaiting.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/ResentQnaPosts.tsx
  src/app/(home)/(posts)/archive/page.tsx
  src/app/(home)/(posts)/forum/page.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Replies.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Reply.tsx
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useAddReplyMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useEditReplyMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/useKebob.ts
  src/app/(home)/(posts)/qna/page.tsx
  src/app/(home)/(profile)/_components/ProfileSetting.tsx
  src/app/(home)/(profile)/_components/myactivities/BookmarksList.tsx
  src/app/(home)/(profile)/_components/myactivities/LikesList.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/CheckCurrentPassword.tsx
  src/app/(home)/(profile)/_components/setting/profilemodal/PasswordModal.tsx
  src/app/(home)/(search)/_components/Search.tsx
  src/app/(home)/(search)/_components/SearchPostCard.tsx
  src/app/(home)/_components/MainPageTag.tsx
  src/app/(home)/layout.tsx
  src/app/api/common/index.ts
  src/app/api/posts/archive-detail/[id]/route.ts
  src/app/api/posts/forum-detail/forum-comments/index.ts
  src/app/api/posts/forum-detail/forum-reply/index.ts
  src/app/api/posts/forum/all-forum/route.ts
  src/app/api/posts/forum/route.ts
  src/app/api/profile/reset-password/route.ts
  src/app/api/profile/verify-password/route.ts
  src/app/api/upsert/tags/[id]/route.ts
  src/app/globals.css
  src/app/layout.tsx
  src/assets/images/common/UserProfileIcon.tsx
  src/components/common/PaddingOrNot.tsx
  src/components/common/SearchPadding.tsx
  src/components/header/Header.tsx
  src/components/header/UserMenu.tsx
  src/constants/TagList.ts
  src/hooks/common/useNicknameValidation.ts
  src/hooks/forum/useFetchForumPosts.ts
  src/hooks/forum/useFetchTopLikedPosts.ts
  src/libs/index.ts
  src/types/index.ts
  src/utils/imageUpload.ts
Labels: fix

#366 style: serchpage_skeleton
  src/app/(home)/(search)/_components/Search.tsx
  src/app/(home)/(search)/_components/SearchSkeletonCard.tsx
  src/app/(home)/(search)/_components/SearchSkeletonUi.tsx
  src/app/globals.css
Labels: Styling

#368 fix: mobile qna datail page edit answer
  src/app/(home)/(posts)/qna/[id]/_components/QnaPost.tsx
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/QuestionKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaQuestion.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
  src/app/api/upsert/posting/route.ts
  src/components/common/Chip.tsx
Labels: fix

#369 Fix: LibaryDetail
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveInputComment.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReplyInput.tsx
  src/app/(home)/(posts)/_components/archive-detail/skeleton/ArchiveDetailSkeleton.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
Labels: Styling, fix

#372 fix: 포스트 삭제 경로 수정
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
Labels: fix

#375 Feature/readme
  README.md
  image-1.png
  image.png
  src/app/(home)/(auth)/_components/LoginForm.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
Labels: fix

#379 Fix/myfunction error
  src/app/(home)/(profile)/_components/myactivities/MyPostsList.tsx
  src/app/(home)/(search)/_components/Search.tsx
  src/app/(home)/(search)/_components/SearchFilter.tsx
  src/app/(home)/(search)/_components/SearchPostCard.tsx
  src/app/(home)/(search)/_components/SearchSkeletonCard.tsx
  src/app/api/profile/myposts/route.ts
  src/components/categoryfilter/ContentFilters.tsx
  src/components/categoryfilter/ForumToggle.tsx
  src/components/categoryfilter/SortingFilters.tsx
Labels: fix

#374 fix debounce
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveInputComment.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReplyInput.tsx
  src/app/(home)/(posts)/_components/archive/ArchivePosts.tsx
  src/app/(home)/(posts)/_components/forum/card/PostCard.tsx
  src/app/(home)/(posts)/_components/forum/card/PostHeader.tsx
  src/app/(home)/(posts)/_components/qna/resent-qna/QnaPostItemSelected.tsx
  src/app/(home)/(posts)/archive/[id]/page.tsx
  src/components/header/SearchBar.tsx
  src/utils/markdownCut.ts
Labels: fix

#382 Style: libary
  src/app/(home)/(posts)/_components/archive-detail/ArchiveInputComment.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveReply.tsx
Labels: Styling

#384 Update README.md
  README.md
Labels: Styling

#385 fix: qna detail error
  src/app/(home)/(posts)/qna/[id]/_components/kebob-btn/QuestionKebobBtn.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswers.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaQuestion.tsx
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useAddReplyMutation.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useReplyForm.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/useDeleteMutation.ts
Labels: fix

#388 fix error
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/forum/ForumPostsWithCategoryAndSort.tsx
  src/components/common/BookmarkButton.tsx
  src/components/common/LikeButton.tsx
Labels: fix

#389 fix: upsert invalidateQuery
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/Reply.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-comments/ReplyForm.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/PostingAnswerArea.tsx
  src/app/(home)/(posts)/qna/[id]/_components/qna-post/QnaAnswer.tsx
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useReply.ts
  src/app/(home)/(posts)/qna/[id]/_hooks/reply/useReplyForm.ts
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
Labels: fix

#390 fix: myppostlist apply invalidateQuery
  src/app/(home)/(profile)/_components/myactivities/MyPostsList.tsx
Labels: fix

#391 fix: library
  src/app/(home)/(posts)/_components/archive-detail/ArchiveComments.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveDetailPost.tsx
  src/app/(home)/(posts)/_components/archive-detail/ArchiveInputComment.tsx
Labels: fix

#393 fix: upsert Loading
  src/app/(home)/(upsert)/_components/edit/EditForm.tsx
  src/app/(home)/(upsert)/_components/posting/PostingForm.tsx
Labels: fix

#394 fix: error
  src/app/(home)/(profile)/_components/myactivities/BookmarksList.tsx
  src/app/(home)/(profile)/_components/myactivities/LikesList.tsx
  src/providers/BookmarkProvider.tsx
  src/providers/LikeProvider.tsx
  src/types/buttons/bookmark.ts
  src/types/buttons/like.ts
Labels: fix
